created autogen script for generating subaddresses

diff --git a/autogen b/autogen
--- a/autogen
+++ b/autogen
@@ -1,10 +1,13 @@
 #!/bin/bash
-ARGS=$(getopt --options vhc:o: --long "verbose,help,output-file:" -- "$@")
+ARGS=$(getopt --options vhc:o:n:p: --long "verbose,help,output-file:,wallet-name:,password:" -- "$@")
 eval set -- "$ARGS"
 verbose="false"
 help="false"
 count=50
 output_file="addresses.txt"
+
+wallet_name=""
+wallet_password=""
 
 while true; do
     case "$1" in
@@ -12,6 +15,8 @@ while true; do
         -h|--help) help="true"; shift ;;
 	-c) count="$2"; shift 2 ;;
 	-o|--output-file) output_file="$2"; shift 2 ;;
+	-n|--wallet-name) wallet_name="$2"; shift 2 ;;
+	-p|--password) wallet_password="$2"; shift 2 ;;
         --) break ;;
         *) printf "Unknown option %s\n" "$1"; exit 1 ;;
     esac
@@ -25,7 +30,34 @@ if [ "$help" = "true" ]; then
     exit 0
 fi   
 
+if [ -z "$wallet_name" ]; then
+    echo "Wallet File Location must be specified with -n or --wallet-name"
+    exit 0
+fi
 
-for ((i=1; i<=count; i++)); do
-    echo "$i" >> "$output_file"  # Append the loop index to the file
-done
+
+if [ -z "$wallet_password" ]; then
+    echo "Please enter your Wallet Password: "
+    read -s password
+    echo
+fi
+
+#TODO: dynamically find alternative paths for cli or assume it's in PATH
+monero_wallet_cli_path="/home/linuxbrew/.linuxbrew/bin/monero-wallet-cli"
+
+if [ ! -f "$monero_wallet_cli_path" ]; then
+    echo "Error: monero-wallet-cli script not found!"
+    exit 1
+fi
+
+#TODO: throw error if wallet file or password is incorrect
+
+{
+	for ((i=1; i<=count; i++)); do
+		echo address new
+	done
+	echo "exit"
+} | "$monero_wallet_cli_path" --wallet-file "$wallet_name" --password  "$wallet_password" | grep -oP '\d+\s+[A-Za-z0-9]{95}' | awk '{print $2}' >> "$output_file" 2>$1
+
+
+echo "Generated $count subaddress(es) and wrote to $output_file."
